import type { Metadata } from "next";
import {ReactNode} from "react";
import "./globals.css";


export const metadata: Metadata = {
  title: "NoteHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: { children: ReactNode; modal: ReactNode; }) {
  return (
    <html lang="en">
      <body>
        {children}
        {modal}
      </body>
    </html>
  );
}
